// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqzihcxcbpzuojndfizj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxemloY3hjYnB6dW9qbmRmaXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzUzODMsImV4cCI6MjA2MDMxMTM4M30.lb0KsoDwxajnokIAhuOpaetoF8OR91I5Unov-Le0Q1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);